clear all; close all; clc


% Given matrix A 
A = [1 2; 4 5] ; 

%% PART A: Use MATLAB to find the SINGULAR VALUE DECOMP. (SVD) of the given matrix A
[U,Sig,V] = svd(A)         % Performs a SVD of matrix A 
                        
checkA = U * Sig * V' ;    % Checks that it outputs the same matrix A  (A = U * S * V' ----> similar to A = V * D * V')  


%% PART B: Write code to make a set of points, giving a UNIT CIRCLE (S) 
theta = linspace(0, 2*pi, 100);


%%%%% Parametrization of a UNIT CIRCLE ----> r = 1  %%%%%
n = length(theta)  ;

% Length of the principal axes of the unit circle (S)
S(1, 1:n) = sin(theta)  ;           % y = rsin(theta) 
S(2, 1:n) = cos(theta)  ;           % x = rsin(theta)  


% Find eigenvectors
[V, D] = eig(A);

magv1 = sqrt(V(1)^2+V(2)^2);
magv2 = sqrt(V(1)^2+V(2)^2);


% Plot of the UNIT CIRCLE (S) 
figure(1)
plot([0 V(1,1)], [0 V(2,1)], 'r', 'LineWidth', 2)
hold on
plot([0 V(1,2)], [0 V(2,2)], 'b', 'LineWidth', 2)
hold on
plot(S(1,:), S(2,:), '--or')       
legend('eigvector 1','eigvec2')
title('Unit circle (S) generated by a set of points', 'FontSize', 14)
xlabel('x')
ylabel('y')
xlim([-2 2]) ;          % Extend the bounds on the x-axis 
ylim([-2 2]) ;          % Extend the bounds on the y-axis 



%% PART C: Apply matrix A to S to get resulting ELLIPSE
AS = A * S  ;                 % Length of the principal semi-axes of the ellipse 


o1 = Sig(1,1);
u1 = U(:,1);
o2 = Sig(2,2);
u2 = U(:,2);


vec1 = o1*u1
vec2 = o2*u2

% Plot of the ELLIPSE (AS) 
figure(2)
plot([0 vec1(1)], [0 vec1(2)], 'r', 'LineWidth', 2)
hold on
plot([0 vec2(1)], [0 vec2(2)], 'b', 'LineWidth', 2)
hold on
plot(AS(1,:), AS(2,:), '--ob')    
axis([-8 8 -8 8])
title('Stretching the unit circle under a 2x2 matrix A transformation', 'FontSize', 14)
xlabel('x')
ylabel('y')

%%

figure(3)


theta = linspace(0, 2*pi, 100);


%%%%% Parametrization of a UNIT CIRCLE ----> r = 1  %%%%%
n = length(theta)  ;

% Length of the principal axes of the unit circle (S)
S(1, 1:n) = sin(theta)  ;           % y = rsin(theta) 
S(2, 1:n) = cos(theta)  ;           % x = rsin(theta)  


% Find eigenvectors
[V, D] = eig(A);

% Plot of the UNIT CIRCLE (S) 
figure(3)
plot([0 V(1,1)], [0 V(2,1)], 'r', 'LineWidth', 2)
hold on
plot([0 V(1,2)], [0 V(2,2)], 'b', 'LineWidth', 2)
hold on
plot(S(1,:), S(2,:), '--or')       



AS = A * S  ;                 % Length of the principal semi-axes of the ellipse 


o1 = Sig(1,1);
u1 = U(:,1);
o2 = Sig(2,2);
u2 = U(:,2);


vec1 = o1*u1;
vec2 = o2*u2;

magitude_v1 = sqrt(vec1(1)^2+vec1(2)^2)
magitude_v2 = sqrt(vec2(1)^2+vec2(2)^2)


% Plot of the ELLIPSE (AS) 
hold on
plot([0 vec1(1)], [0 vec1(2)], 'r', 'LineWidth', 2)
hold on
plot([0 vec2(1)], [0 vec2(2)], 'b', 'LineWidth', 2)
hold on
plot(AS(1,:), AS(2,:), '--ob')    
axis([-8 8 -8 8])
title('Stretching the unit circle under a 2x2 matrix A transformation', 'FontSize', 14)
xlabel('x')
ylabel('y')